### ISSUE TITLE
Site hangs if MIDI file contains no piano

### ISSUE THREAD

**Issue by redcatbrad** [addisonvex/midi2vidi-public#1]
hey, bro can u make the time shorter cuz i have been waiting like 20 minutes to visuize this midi and its still not done!!!! {midi is in a zip cuz github dont allow me to upload .mid files]
[the midi file.zip](https://github.com/user-attachments/files/16289180/the.midi.file.zip)

**Comment by addisonvex** [comment]
Hello @redcatbrad, and thanks for your comment! I've had a look at your MIDI file. There are two issues that I'll deal with separately:

1. The site doesn't process MIDI files that contain no keyboard data at the moment, i.e. files where the programs (instruments) are non-piano. Your file contains tracks with guitars, synth leads, bass, pads, drums, and other effects, but no piano! In case you appreciate the detail, program numbers can be found at https://en.wikipedia.org/wiki/General_MIDI, and the midi2vidi should work if the program below 9 are included.

To resolve this, would it help if I provided a checkbox on the page that optionally included _all_ instruments and not just piano? I'd have to consider removing drum tracks and other effects that wouldn't be appropriate to see on a keyboard. Or do you have any other suggestions?

2. If the site doesn't process a MIDI file correctly, it appears to hang and will leave users sitting around indefinitely. I'll have a look at providing a better user experience on failure this weekend!

I hope that helps!
Dave

**Comment by redcatbrad** [comment]
the checkbox idea sounds perfect! i think that is good.

**Comment by addisonvex** [comment]
Hi @redcatbrad. I've attached what happens if I include all the instruments, and it looks like a bit of a mess to me! Is this what you were expecting, or were you interested in seeing just the melody played or something? The problem is that there are around 9 different instruments, and this is what happens if you play them all at once on a keyboard.
[RED_ZONE video.zip](https://github.com/user-attachments/files/16326143/RED_ZONE.video.zip)

**Comment by addisonvex** [comment]
An error will now be displayed if the MIDI file contains no piano notes played instead of hanging indefinitely. Where there are multiple musical instruments on a MIDI track, and especially if there is no piano part, I see no good way of selecting which parts should be represented on a keyboard from those not. I'll consider a feature allowing users to select which parts should be played should there be further demand for it.
